import { ImageResponse } from "next/og";
import { NextRequest } from "next/server";

export const runtime = "edge";

const BASE = "https://rizzjobs.in";

const SECTION_COLORS: Record<string, { bg: string; accent: string; label: string }> = {
  cricket: { bg: "#0A0A0F", accent: "#FFB800", label: "Cricket" },
  ipl: { bg: "#0A0A0F", accent: "#FFB800", label: "IPL 2026" },
  news: { bg: "#070708", accent: "#f0a500", label: "News" },
  govjobs: { bg: "#030712", accent: "#6366f1", label: "Gov Jobs" },
};

async function fetchFont(url: string): Promise<ArrayBuffer | null> {
  try {
    const res = await fetch(url, { next: { revalidate: 86400 } });
    if (!res.ok) return null;
    return res.arrayBuffer();
  } catch {
    return null;
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const type = searchParams.get("type") ?? "section";

  // Load Inter font (used across all cards).
  // Must be TTF/OTF/WOFF v1 - satori cannot parse woff2. The previous
  // fonts.gstatic woff2 URL made every render throw and fall back silently.
  const interFontUrl = "https://cdn.jsdelivr.net/npm/@fontsource/inter@5.1.0/files/inter-latin-700-normal.woff";
  const fontData = await fetchFont(interFontUrl);

  const fonts = fontData
    ? [{ name: "Inter", data: fontData, style: "normal" as const, weight: 700 as const }]
    : [];

  // ── Section hub card ──────────────────────────────────────────────────────
  if (type === "section") {
    const section = searchParams.get("section") ?? "govjobs";
    const cfg = SECTION_COLORS[section] ?? SECTION_COLORS.govjobs;

    return new ImageResponse(
      (
        <div
          style={{
            width: 1200,
            height: 630,
            background: cfg.bg,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: "Inter, sans-serif",
            position: "relative",
          }}
        >
          {/* Glow blob */}
          <div
            style={{
              position: "absolute",
              top: -100,
              left: -100,
              width: 500,
              height: 500,
              borderRadius: "50%",
              background: `radial-gradient(circle, ${cfg.accent}33, transparent 70%)`,
            }}
          />
          {/* Site name */}
          <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 24 }}>
            <div
              style={{
                width: 48,
                height: 48,
                borderRadius: 12,
                background: cfg.accent,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 24,
                color: "#000",
                fontWeight: 700,
              }}
            >
              R
            </div>
            <span style={{ fontSize: 20, color: "#aaa", fontWeight: 700, letterSpacing: 4 }}>
              RIZZ JOBS
            </span>
          </div>
          {/* Section label */}
          <div
            style={{
              fontSize: 72,
              fontWeight: 700,
              color: cfg.accent,
              letterSpacing: -2,
              marginBottom: 16,
            }}
          >
            {cfg.label}
          </div>
          <div style={{ fontSize: 22, color: "#666", letterSpacing: 2 }}>rizzjobs.in</div>
        </div>
      ),
      { width: 1200, height: 630, fonts }
    );
  }

  // ── Exam / Government Job card ────────────────────────────────────────────
  // Doubles as the notification hero banner (generated by the scraper and the
  // admin Generate Banner button), so it is styled richer than the other cards.
  if (type === "exam") {
    const title = searchParams.get("title") ?? "Government Job Notification";
    const deadline = searchParams.get("deadline") ?? "";
    const category = searchParams.get("category") ?? "Gov Jobs";
    const truncTitle = title.length > 110 ? title.slice(0, 110) + "…" : title;
    const titleSize = truncTitle.length <= 50 ? 54 : truncTitle.length <= 80 ? 46 : 38;

    return new ImageResponse(
      (
        <div
          style={{
            width: 1200,
            height: 630,
            background: "linear-gradient(135deg, #050814 0%, #0a102c 50%, #141042 100%)",
            display: "flex",
            flexDirection: "column",
            padding: "56px 72px",
            fontFamily: "Inter, sans-serif",
            position: "relative",
          }}
        >
          {/* Accent top border */}
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: 1200,
              height: 6,
              background: "linear-gradient(90deg, #6366f1 0%, #8b5cf6 50%, #06b6d4 100%)",
              display: "flex",
            }}
          />
          {/* Glow bottom right */}
          <div
            style={{
              position: "absolute",
              bottom: -140,
              right: -120,
              width: 640,
              height: 520,
              background: "radial-gradient(circle, #6366f12e, transparent 65%)",
              display: "flex",
            }}
          />
          {/* Shield watermark */}
          <svg
            width={360}
            height={420}
            viewBox="0 0 24 24"
            style={{ position: "absolute", right: 30, top: 140 }}
          >
            <path
              d="M12 2 L20.5 5.5 V11.5 C20.5 16.6 17 21 12 22.5 C7 21 3.5 16.6 3.5 11.5 V5.5 Z"
              fill="#6366f1"
              fillOpacity={0.07}
              stroke="#818cf8"
              strokeOpacity={0.18}
              strokeWidth={0.4}
            />
            <path
              d="M8.5 12 L11 14.5 L15.5 9.5"
              stroke="#818cf8"
              strokeOpacity={0.22}
              strokeWidth={0.8}
              fill="none"
            />
          </svg>

          {/* Top bar */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 44 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <div
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: 10,
                  background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: 20,
                  color: "#fff",
                  fontWeight: 700,
                }}
              >
                R
              </div>
              <span style={{ fontSize: 17, color: "#818cf8", fontWeight: 700, letterSpacing: 3 }}>RIZZ JOBS</span>
            </div>
            <span
              style={{
                fontSize: 14,
                color: "#a5b4fc",
                background: "#6366f120",
                border: "1px solid #6366f14d",
                borderRadius: 8,
                padding: "6px 16px",
                fontWeight: 700,
                letterSpacing: 2,
              }}
            >
              {category.toUpperCase()}
            </span>
          </div>

          {/* Title (vertically centered in the free space) */}
          <div
            style={{
              flex: 1,
              display: "flex",
              alignItems: "center",
              marginBottom: 28,
              maxWidth: 860,
            }}
          >
            <div
              style={{
                fontSize: titleSize,
                fontWeight: 700,
                color: "#f4f4f8",
                lineHeight: 1.22,
                letterSpacing: -0.5,
              }}
            >
              {truncTitle}
            </div>
          </div>

          {/* Bottom row */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
              {deadline ? (
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10,
                    background: "#ef444414",
                    border: "1px solid #ef444440",
                    borderRadius: 8,
                    padding: "8px 18px",
                  }}
                >
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#ef4444", display: "flex" }} />
                  <span style={{ fontSize: 17, color: "#f87171", fontWeight: 700 }}>Last Date: {deadline}</span>
                </div>
              ) : (
                <span
                  style={{
                    fontSize: 14,
                    color: "#64748b",
                    fontWeight: 700,
                    letterSpacing: 2,
                  }}
                >
                  OFFICIAL NOTIFICATION UPDATE
                </span>
              )}
            </div>
            <span style={{ fontSize: 17, color: "#4c4f6b", fontWeight: 700 }}>rizzjobs.in</span>
          </div>
        </div>
      ),
      { width: 1200, height: 630, fonts }
    );
  }

  // ── IPL Match card ─────────────────────────────────────────────────────────
  if (type === "ipl-match") {
    const team1 = searchParams.get("team1") ?? "Team 1";
    const team2 = searchParams.get("team2") ?? "Team 2";
    const status = searchParams.get("status") ?? "";
    const isLive = searchParams.get("live") === "1";

    return new ImageResponse(
      (
        <div
          style={{
            width: 1200,
            height: 630,
            background: "#0A0A0F",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: "Inter, sans-serif",
            position: "relative",
          }}
        >
          {/* Glow */}
          <div
            style={{
              position: "absolute",
              top: -150,
              left: "50%",
              transform: "translateX(-50%)",
              width: 700,
              height: 400,
              background: "radial-gradient(circle, #FFB80022, transparent 70%)",
            }}
          />

          {/* Header */}
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 48 }}>
            {isLive && (
              <div
                style={{
                  background: "#ef4444",
                  color: "#fff",
                  fontSize: 13,
                  fontWeight: 700,
                  padding: "4px 12px",
                  borderRadius: 6,
                  letterSpacing: 2,
                }}
              >
                LIVE
              </div>
            )}
            <span style={{ color: "#FFB800", fontSize: 18, fontWeight: 700, letterSpacing: 4 }}>
              IPL 2026
            </span>
          </div>

          {/* Teams */}
          <div style={{ display: "flex", alignItems: "center", gap: 48, marginBottom: 32 }}>
            <span style={{ fontSize: 52, fontWeight: 700, color: "#fff" }}>{team1}</span>
            <span style={{ fontSize: 36, color: "#FFB800", fontWeight: 700 }}>VS</span>
            <span style={{ fontSize: 52, fontWeight: 700, color: "#fff" }}>{team2}</span>
          </div>

          {/* Status */}
          {status && (
            <div
              style={{
                fontSize: 18,
                color: "#aaa",
                textAlign: "center",
                maxWidth: 800,
                marginBottom: 48,
              }}
            >
              {status}
            </div>
          )}

          {/* Footer */}
          <div style={{ position: "absolute", bottom: 40, display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 14, color: "#555", letterSpacing: 2 }}>RIZZ JOBS</span>
            <span style={{ color: "#333" }}>•</span>
            <span style={{ fontSize: 14, color: "#555" }}>rizzjobs.in/cricket/ipl</span>
          </div>
        </div>
      ),
      { width: 1200, height: 630, fonts }
    );
  }

  // ── IPL Player card ────────────────────────────────────────────────────────
  if (type === "ipl-player") {
    const name = searchParams.get("name") ?? "Player Name";
    const team = searchParams.get("team") ?? "";
    const role = searchParams.get("role") ?? "Cricketer";

    return new ImageResponse(
      (
        <div
          style={{
            width: 1200,
            height: 630,
            background: "#0A0A0F",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: "Inter, sans-serif",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 32 }}>
            <span style={{ color: "#FFB800", fontSize: 16, fontWeight: 700, letterSpacing: 4 }}>
              IPL 2026
            </span>
          </div>
          <div style={{ fontSize: 64, fontWeight: 700, color: "#fff", marginBottom: 12, letterSpacing: -1 }}>
            {name}
          </div>
          {team && (
            <div style={{ fontSize: 24, color: "#FFB800", marginBottom: 8 }}>{team}</div>
          )}
          <div style={{ fontSize: 18, color: "#666" }}>{role}</div>
          <div style={{ position: "absolute", bottom: 40, fontSize: 14, color: "#444", letterSpacing: 2 }}>
            RIZZJOBS.IN
          </div>
        </div>
      ),
      { width: 1200, height: 630, fonts }
    );
  }

  // ── News section card ──────────────────────────────────────────────────────
  if (type === "news-section") {
    const category = searchParams.get("category") ?? "finance";
    const labels: Record<string, string> = {
      finance: "Finance News",
      business: "Business News",
      markets: "Markets",
      economy: "Economy",
      startups: "Startups",
    };
    const label = labels[category] ?? "News";

    return new ImageResponse(
      (
        <div
          style={{
            width: 1200,
            height: 630,
            background: "#070708",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: "Inter, sans-serif",
            position: "relative",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: -100,
              right: -100,
              width: 500,
              height: 500,
              background: "radial-gradient(circle, #f0a50022, transparent 70%)",
            }}
          />
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24 }}>
            <span style={{ color: "#f0a500", fontSize: 16, fontWeight: 700, letterSpacing: 4 }}>
              RIZZ JOBS
            </span>
          </div>
          <div style={{ fontSize: 72, fontWeight: 700, color: "#fff", marginBottom: 16 }}>{label}</div>
          <div style={{ fontSize: 20, color: "#666" }}>India&apos;s fastest financial news</div>
          <div style={{ position: "absolute", bottom: 40, fontSize: 14, color: "#444", letterSpacing: 2 }}>
            RIZZJOBS.IN/NEWS/{category.toUpperCase()}
          </div>
        </div>
      ),
      { width: 1200, height: 630, fonts }
    );
  }

  // ── Fallback ───────────────────────────────────────────────────────────────
  return new ImageResponse(
    (
      <div
        style={{
          width: 1200,
          height: 630,
          background: "#030712",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontFamily: "Inter, sans-serif",
        }}
      >
        <div style={{ fontSize: 48, fontWeight: 700, color: "#6366f1" }}>Rizz Jobs</div>
      </div>
    ),
    { width: 1200, height: 630, fonts }
  );
}
